services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    image: green-finder
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./uploaded_data:/app/uploaded_data    # アップロードされたファイルを保存するディレクトリ（必要に応じて）
    environment:
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=200
      - STREAMLIT_SERVER_PORT=8080
    restart: always